.\" See COPYING file for copyright, license and warranty details.
.TH SPOUT 1 spout\-1.4
.SH NAME
spout \- a simple caveflying game.
.SH SYNOPSIS
.B spout
.RB [-f]
.RB [-z\ zoom]
.SH DESCRIPTION
Spout is a simple caveflying game. The object is to get as high
as possible, avoiding or destroying obstacles.
.SH OPTIONS
.TP
.B \-f
Fullscreen
.TP
.B \-z zoom
Zooms the screen by zoom times (default: 4)
.SH USAGE
.TP
.B Left
Rotate left
.TP
.B Right
Rotate right
.TP
.B Space
Thrust
.TP
.B Escape
Pause
.TP
.B Shift\-Escape
Quit
